namespace StudentGradesTable
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
    void CalculateAverages(Object sender, Microsoft.UI.Xaml.RoutedEventArgs e);
    void UpdateGrades(Object sender, Microsoft.UI.Xaml.RoutedEventArgs e);  // ← ДОБАВИЛИ
    }
}
